stages:
  - trigger
  - build
  - test

# Generate child pipelines
factory:
  stage: trigger
  tags:
    - sandbox
  only:
    - develop
  script:
    # Execute CI factory and pass the last used tag
    - export LAST_TAG=$(git describe --tags --abbrev=0)
    - echo "Building ASUP Release ${LAST_TAG}"
    - ./ci-factory.sh ${LAST_TAG}
    - ./build.sh
  artifacts:
    expire_in: 1 week
    paths:
      - .env
      - .gitlab-ci-child-build-dynamic.yml
      - .gitlab-ci-child-test-dynamic.yml

# Build releases
trigger:build:
  stage: build
  trigger:
    include:
      - artifact: .gitlab-ci-child-build-dynamic.yml
        job: factory
  needs:
    - job: factory
      artifacts: true

# Test releases
trigger:test:
  stage: test
  trigger:
    include:
      - artifact: .gitlab-ci-child-test-dynamic.yml
        job: factory
  needs:
    - job: factory
      artifacts: true
    - job: trigger:build