stages:
  - trigger
  - build
  - test

# Generate child pipelines
.factory: &factory
  stage: trigger
  tags:
    - sandbox
  artifacts:
    expire_in: 1 week
    paths:
      - .env
      - .gitlab-ci-child-build-dynamic.yml
      - .gitlab-ci-child-test-dynamic.yml

factory:develop:
  <<: *factory
  only:
    - develop
  script:
    # Execute CI factory and pass the last used tag
    - export LAST_TAG="dev"
    - echo "Building ASUP Release ${LAST_TAG}"
    - ./ci-factory.sh ${LAST_TAG} ${DEV}
    - ./build.sh

# Build develop releases
trigger:build:develop:
  stage: build
  trigger:
    include:
      - artifact: .gitlab-ci-child-build-dynamic.yml
        job: factory:develop
  needs:
    - job: factory:develop
      artifacts: true

# Test develop releases
trigger:test:
  stage: test
  trigger:
    include:
      - artifact: .gitlab-ci-child-test-dynamic.yml
        job: factory:develop
  needs:
    - job: factory:develop
      artifacts: true
    - job: trigger:build


factory:production:
  <<: *factory
  only:
    - master
  script:
    # Execute CI factory and pass the last used tag
    - export LAST_TAG=$(git describe --tags --abbrev=0)
    - echo "Building ASUP Release ${LAST_TAG}"
    - ./ci-factory.sh ${LAST_TAG} ${DEV}
    - ./build.sh

# Build releases
trigger:build:production:
  stage: build
  trigger:
    include:
      - artifact: .gitlab-ci-child-build-dynamic.yml
        job: factory:production
  needs:
    - job: factory:production
      artifacts: true
